set(APPLICATION_DESCRIPTION "vozer")
set(APPLICATION_ID "com.gnovit.vozer")
set(APPLICATION_NAME vozer)
set(APPLICATION_URL "https://www.vozer.site")
set(APPLICATION_VENDOR "Gnovit Communications")
set(APPLICATION_LICENCE "GNU General Public License V3")
set(APPLICATION_LICENCE_URL "https://www.gnu.org/licenses/gpl-3.0.html")
set(APPLICATION_START_LICENCE "2010")

set(EXECUTABLE_NAME vozer)
